#!/usr/bin/expect

#set file [ls -t -r | tail -n 1]
spawn ftp 10.0.0.2
expect "liu):"
send "liuyanming\n"
expect "Password:"
send "y2m8d7a9\n"
expect "ftp>"
send "cd 00\n"
#expect "ftp>"
#send "get $file\n"
#expect "ftp>"
#send "exit\n"
#expect "bye."

interact

