#!/bin/bash

interface=wlp9s0
if [ $# -eq 1 ];then
	interface=$1
fi

#sudo systemctl stop NetworkManager.service start
sudo airmon-ng stop $interface
sudo iwconfig $interface essid 1freenet
sudo dhclient $interface
